vim.cmd("cd  C:/Users/ZGN1/AppData/Local/nvim")
-- vim.cmd("cd  C:/Users/ZGN1/Rworks")
require("zgn1.plugins-setup")
require("zgn1.core.options")
require("zgn1.core.keymaps")
require("zgn1.core.colorscheme")
require("zgn1.plugins.comment")
require("zgn1.plugins.nvim-tree")
require("zgn1.plugins.lualine2")
require("zgn1.plugins.telescope")
require("zgn1.plugins.nvim-cmp")
require("zgn1.plugins.lsp.mason")
require("zgn1.plugins.lsp.lspsaga")
require("zgn1.plugins.lsp.lspconfig")
require("zgn1.plugins.lsp.null-ls")
require("zgn1.plugins.autopairs")
require("nvim-treesitter.install").compilers = { "clang" }
require("zgn1.plugins.treesitter")
require("zgn1.plugins.gitsigns")
require("zgn1.plugins.tabline")
require("zgn1.plugins.leap")
